name: kg-bio 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - jupyterlab=3
  - jupyter-offlinenotebook
  - pandas=1.3.5
  - pyarrow=7.0.0
  - dask
  - beautifulsoup4
  - aiohttp
  - requests
  - xlrd
  - openpyxl=2.6.0
  - lxml
  - ipywidgets=7.6.2
  - black
  - pip
  - pip:
    - pybiopax==0.1.0
